version: "2"
services:
  app:
    image: golang:latest
    volumes:
      - .:/app
    working_dir: /app
    command: go run main.go
    ports:
      - '3000:3000'
    links:
      - redis
  redis:
    image: redis
    ports:
      - '6379:6379'
    environment:
      SERVICE_TAGS: redis-cluster:test